name: Continous Integration
on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    
    - name: Install mongodb
      uses: supercharge/mongodb.github-actions@1.8.0
      with:
        mongodb-version: '6'
    
    - name: Install dependencies
      run: npm install

    - name: Execute integration tests
      run: npm run test